import { createPublicKey, verify } from 'node:crypto';
import * as fc from 'fast-check';
import { describe, expect, it } from 'vitest';
import { AssertionSigner } from '../src/assertion.js';
import { base64UrlDecode, base64UrlEncode, fromUtf8 } from '../src/encoding.js';
import { SubactIdError } from '../src/errors.js';
import { ecPem, rsaPem } from './keys.js';

// Property-based tests: each statement below is tried on inputs fast-check generates, and a
// failing input is shrunk to the smallest one that still fails. They cover what this client
// parses by hand out of what a caller gives it, the PEM and DER of an agent's key and the
// base64url of a token, where an example or two says little about the inputs nobody chose.

/** The `alg` in the header of a compact JWS. */
function algOf(jwt: string): string {
  const header = JSON.parse(fromUtf8(base64UrlDecode(jwt.split('.')[0] as string))) as {
    alg: string;
  };
  return header.alg;
}

/** Whether `jwt` verifies with the public half of `pem` under `alg`, as the control plane checks it. */
function verifies(jwt: string, pem: string, alg: string): boolean {
  const [h, c, s] = jwt.split('.') as [string, string, string];
  const key = createPublicKey(pem);
  return verify(
    'sha256',
    Buffer.from(`${h}.${c}`),
    alg === 'ES256' ? { key, dsaEncoding: 'ieee-p1363' } : key,
    base64UrlDecode(s),
  );
}

describe('base64url, on generated bytes', () => {
  it('round-trips any bytes, in the alphabet and without the padding JOSE wants', () => {
    fc.assert(
      fc.property(fc.uint8Array({ maxLength: 512 }), (bytes) => {
        const text = base64UrlEncode(bytes);

        expect(text).toMatch(/^[A-Za-z0-9_-]*$/);
        expect(base64UrlDecode(text)).toEqual(bytes);
      }),
    );
  });
});

describe('AssertionSigner, on generated keys', () => {
  /** Whatever may separate the lines of a PEM: one line ending or several, spaces, tabs. */
  const lineBreaks = fc.string({
    unit: fc.constantFrom(' ', '\t', '\n', '\r\n'),
    minLength: 1,
    maxLength: 4,
  });
  /** Text a PEM may be pasted into the middle of, with no marker of its own. */
  const surroundings = fc.string({ maxLength: 32 }).filter((text) => !text.includes('-----'));
  /** `pem` with its lines rejoined by `lineBreaks`, and `surroundings` on either side of it. */
  const rewrapped = (pem: string): fc.Arbitrary<string> => {
    const lines = pem.trim().split('\n');
    const breaks = fc.array(lineBreaks, {
      minLength: lines.length + 1,
      maxLength: lines.length + 1,
    });
    return fc.tuple(surroundings, breaks, surroundings).map(([before, between, after]) => {
      const body = lines.map((line, i) => `${between[i] ?? ''}${line}`).join('');
      return `${before}${body}${between[lines.length] ?? ''}${after}`;
    });
  };

  it.each([
    ['ES256', ecPem],
    ['RS256', rsaPem],
  ])(
    'reads a %s key however its PEM is line-broken and whatever surrounds it, and signs with it',
    async (alg, pem) => {
      await fc.assert(
        fc.asyncProperty(rewrapped(pem), async (privateKey) => {
          const signer = new AssertionSigner({ agentId: 'a', kid: 'k', privateKey });

          const jwt = await signer.sign('https://cp.example');

          expect(algOf(jwt)).toBe(alg);
          expect(verifies(jwt, pem, alg)).toBe(true);
        }),
        { numRuns: 30 },
      );
    },
  );

  it('refuses a PEM wrapped around bytes that are no key, with nothing but a SubactIdError that does not echo them', async () => {
    await fc.assert(
      fc.asyncProperty(fc.uint8Array({ minLength: 16, maxLength: 512 }), async (bytes) => {
        const body = Buffer.from(bytes).toString('base64');
        const privateKey = `-----BEGIN PRIVATE KEY-----\n${body}\n-----END PRIVATE KEY-----`;
        // Reading the algorithm off the DER is total: whatever the bytes say, the constructor returns.
        const signer = new AssertionSigner({ agentId: 'a', kid: 'k', privateKey });

        const error: unknown = await signer.sign('aud').catch((e: unknown) => e);

        expect(error).toBeInstanceOf(SubactIdError);
        expect((error as Error).message).not.toContain(body);
      }),
    );
  });

  it('refuses any other string with a SubactIdError', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.string({ unit: 'grapheme', minLength: 1, maxLength: 200 }),
        async (privateKey) => {
          const signer = new AssertionSigner({ agentId: 'a', kid: 'k', privateKey });

          await expect(signer.sign('aud')).rejects.toBeInstanceOf(SubactIdError);
        },
      ),
    );
  });
});
